import { Montserrat } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/Navbar";
const montserrat = Montserrat({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={montserrat.className}
      >
        <NavbarDemo/>
        {children}
      </body>
    </html>
  );
}
